### ISSUE TITLE
Cannot run the App on 8080

### ISSUE THREAD

**Issue by Isaacwhyuenac** [fancellu/zio-restful-webservice#1]
Hi,

Thanks for the excellent example of ZIO. It really helps a lot. 

I started the project and cannot curl to all endpoints on 8080. However, I can curl to all 8082 endpoints. I run all the test cases and it works but still, I cannot curl to the 8080 port locally. I am 100% sure the 8080 port is not occupied by others... May I know why ?

**Comment by fancellu** [comment]
Oh, is it working now? Doesn't work for me on 8080 either. Worked fine before!

**Comment by Isaacwhyuenac** [comment]
No It does not work for me. But I kinda check out the older version repo and playing with zio

**Comment by fancellu** [comment]
Try the latest. For some reason the Spark work was breaking things. Very odd

**Comment by Isaacwhyuenac** [comment]
Can confirm it is working now
